# STAMP: Base values.yaml for Camunda 8.8
# ============================================================
# This is an opinionated 1-node starting point for a TAM-assisted
# deployment. Please update the relevant sizing section in orchestration section if desired.
#
# Uses basic auth, login with:
#  user: demo
#  password: demo
#
# This deploys Elasticsearch via subchart, with minimal resources and only 1 master and 1 data node.
# Please edit the Elasticsearch section as needed for larger setups.
#
# Usage:
#   helm repo add camunda https://helm.camunda.io && helm repo update
#   helm upgrade --install camunda camunda/camunda-platform \
#     --version 8.8 \
#     --namespace camunda --create-namespace \
#     -f values-orchestration-cluster.yaml \
#     -f ../values-local-tls.yaml  <--- only if installing locally and you want to access via camunda.example.com
#
# Layer in scenario configs from STAMP on top:
#   -f ../../s3/s3-backups-values.yaml
#   -f ../../auth/entra/entra-oidc-values.yaml
#   etc.
#
# ============================================================

global:
  security:
    authentication:
      method: basic    # basic auth for all components by default
  ingress:
    enabled: true
    className: nginx
    host: "camunda.example.com"
    tls:
      enabled: true
      secretName: camunda-platform

orchestration:
  enabled: true
  contextPath: / # components sit at root path of camunda.example.com

  # GRPC Ingress
  ingress:
    grpc:
      enabled: true
      className: nginx
      host: zeebe-camunda.example.com
      tls:
        enabled: true
        secretName: camunda-platform

  # Orchestration Cluster sizing (must be strings, in double quotes)
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  pvcSize: 10Gi

  # inherits "basic" from global.security.authentication.method; specifying it here again is optional
  security:
    authentication:
      method: basic
      unprotectedApi: false   # protect REST/gRPC APIs
    authorizations:
      enabled: true           # enforce authorizations

connectors:
  enabled: true
  # inherits basic auth from global; this block is optional
  security:
    authentication:
      method: basic

# Deploy Elasticsearch via subchart -- resize as needed
elasticsearch:
  enabled: true
  master:
    replicaCount: 1
    persistence:
      size: 15Gi
    # Increase sizing for better stability
    heapSize: 1g
    resources:
      requests:
        cpu: 0.5
        memory: 1536Mi
      limits:
        cpu: 2
        memory: 3Gi
  data:
    replicaCount: 1
    persistence:
      size: 15Gi
    # Increase sizing for better stability
    heapSize: 1g
    resources:
      requests:
        cpu: 0.5
        memory: 1536Mi
      limits:
        cpu: 2
        memory: 3Gi

# Explicitly disable components that require OIDC / Management Identity
console:
  enabled: false

webModeler:
  enabled: false

optimize:
  enabled: false

identity:
  enabled: false

identityPostgresql:
  enabled: false

identityKeycloak:
  enabled: false

# Prometheus
prometheusServiceMonitor:
  enabled: false