apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: archiver
spec:
  groups:
    - name: archiver
      rules:
        - alert: ArchiverBacklogGrowing
          expr: |-
            (
              (
                delta(
                  (
                    sum by (namespace, partition) (zeebe_camunda_exporter_process_instances_awaiting_archival)
                  )[10m:1m]
                ) >= 0
              )
              and
              (
                sum by (namespace, partition) (zeebe_camunda_exporter_process_instances_awaiting_archival) > 0
              )
            )
            * on (namespace) group_left (label_cloud_camunda_io_sales_plan_type, label_cloud_camunda_io_cluster_plan_type, label_cloud_camunda_io_channel, label_cloud_camunda_io_generation)
            (
              max(kube_namespace_labels) by (namespace, label_cloud_camunda_io_sales_plan_type, label_cloud_camunda_io_cluster_plan_type, label_cloud_camunda_io_channel, label_cloud_camunda_io_generation)
            )
          for: 2h
          annotations:
            summary: Archiver backlog is not decreasing.
            description: The backlog of process instances for partition `{{ $labels.partition }}` awaiting archival in namespace `{{ $labels.namespace }}` has not decreased over the last 2 hours. This may indicate the archiver is falling behind.
            runbook_url: https://cautious-adventure-gg5z6wv.pages.github.io/camunda-runbooks/archiver-backlog-growing
          labels:
            severity: critical
            team: data-layer
