apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: connectors
spec:
  groups:
    - name: connectors
      rules:
        - alert: ConnectorsPodCrashLoopingFor20Minutes
          annotations:
            summary: >-
              Connectors Pod is crash looping for more than 20 minutes
            description: >-
              Namespace: `{{ $labels.namespace }}` Pod: `{{ $labels.pod }}`

              Connectors pod is restarting {{ printf "%.2f" $value }} times / 5 minutes.
            dashboard_url: "d/connectors-overview/connectors-overview?orgId=1&var-namespace={{ $labels.namespace }}"
          expr: |-
            rate(kube_pod_container_status_restarts_total{job="kube-state-metrics", pod=~"connectors-deployment.*"}[10m]) * 60 * 5
            * on (namespace) group_left (label_cloud_camunda_io_sales_plan_type)
            (
              max(kube_namespace_labels) by (namespace, label_cloud_camunda_io_sales_plan_type)
            )
            > 0
          for: 20m
          labels:
            severity: critical
            team: connectors

        - alert: ConnectorsJobWorkerQueueOverflowFor20Minutes
          annotations:
            summary: >-
              Connectors job worker backlog is not decreasing for more than 20 minutes
            description: >-
              Namespace: `{{ $labels.namespace }}` Pod: `{{ $labels.pod }}`

              Job worker backlog is reaching {{ $value }} for more than 20 minutes.
              Check if jobs are progressing and if the cluster needs to be scaled up.
            dashboard_url: "d/connectors-overview/connectors-overview?orgId=1&var-namespace={{ $labels.namespace }}"
          # TODO: make the threshold (25) depend on the max-jobs-active setting
          expr: |-
            max_over_time(executor_queued_tasks{name=~"zeebe_client_thread_pool|camundaClientExecutor"}[5m])
            * on (namespace) group_left (label_cloud_camunda_io_sales_plan_type) (max(kube_namespace_labels) by (namespace, label_cloud_camunda_io_sales_plan_type))
            >= 80
          # TODO Bring the threshold down to 40 when this ticket is done: https://github.com/camunda/camunda/issues/39304
          # Currently this number= nb of connectors(approximately 40) + 40, as there's 1 task queued per connector when idle
          for: 20m
          labels:
            severity: critical
            team: connectors

        - alert: ConnectorsLogsErrorsDetected
          annotations:
            summary: >-
              Connectors logs are showing increasing amounts of errors
            description: >-
              Namespace: `{{ $labels.namespace }}` Pod: `{{ $labels.pod }}`

              Connectors logs are showing {{ $value }} new error events / minute for 20 minutes.
          expr: |-
            rate(logback_events_total{job="connectors-service", level="error", logger!~"io.camunda.connector.runtime.core.outbound.ConnectorJobHandler"}[5m]) * 60
            * on (namespace) group_left (label_cloud_camunda_io_sales_plan_type) (max(kube_namespace_labels) by (namespace, label_cloud_camunda_io_sales_plan_type))
            > 0
          for: 20m
          labels:
            severity: critical
            team: connectors
